DatasetSplitter
vanvalenlab/caliban-toolbox pull request #117
Opened 2020-09-02 23:12 UTC by ngreenwald

This PR creates a DatasetSplitter class. This creates sequentially increasing subsets of a data_dict to enable comparisons of accuracy with increasing dataset size. Each larger split contains all of the data in the smaller splits, plus whatever incremental additional samples are needed for the specified size. This ensures that all of the data in previous splits is seen in each subsequent split.

2020-09-30 17:22 UTC, willgraf requested changes
Why does this need to create so many splits?

Why not just have a function that splits the data according to a single split value?

2020-09-30 17:22 UTC, willgraf commented on caliban_toolbox/dataset_splitter.py
> +            raise ValueError('X and y must be keys in the training dictionary')
Just check if the key is in the dictionary, not if its in the keys.  `keys()` creates a new list and the lookup goes from O(1) to O(n).

```suggestion
        if 'X' not in train_dict or 'y' not in train_dict:
            raise ValueError('X and y must be keys in the training dictionary')
```

2020-09-30 17:22 UTC, willgraf commented on caliban_toolbox/dataset_splitter.py
> +                                                                 idx + 1, splits[idx + 1]))
Why not just sort the list of splits?

2020-09-30 17:22 UTC, willgraf commented on caliban_toolbox/dataset_splitter.py
> +            split_dict[str(split)] = new_train_dict
Why cast this to a string?

2020-09-30 23:05 UTC, ngreenwald commented
The reason we have all of these splits is because we want to use this to assess how accuracy changes with dataset size. So we specify in advance all of the different splits of the dataset we want, and then train a model on each for benchmarking purposes.

2020-10-01 20:26 UTC, willgraf requested changes

2020-10-01 20:26 UTC, willgraf commented on caliban_toolbox/dataset_splitter_test.py
> +    assert ds.splits == splits
`splits` is the same list as `ds.splits`, and this test will pass if you comment out the `splits.sort()`. Instead, maybe you can make an assertion about the elements of the list.

2020-10-01 23:09 UTC, ngreenwald commented
The reason Dave initially casted the keys of the dict to strings was so that the dict can be saved as NPZ file. NPZ doesn't allow float keys, so I switched it back to strings in this version.

2020-10-02 22:00 UTC, willgraf commented on caliban_toolbox/dataset_splitter.py
> +            split_dict[str(split)] = new_train_dict
As mentioned elsewhere, it is cast to a string for JSON format.

2020-10-02 22:00 UTC, willgraf approved these changes

2020-10-02 22:09 UTC, merged